// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLQ9SFqdDeeQxdDvHdeYCad4ZBEVINV5E',
    appId: '1:253213775944:web:cfabbdbad991f98cb7607d',
    messagingSenderId: '253213775944',
    projectId: 'gestionfournitures-2e8db',
    authDomain: 'gestionfournitures-2e8db.firebaseapp.com',
    databaseURL: 'https://gestionfournitures-2e8db-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gestionfournitures-2e8db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPd1iE9yuMELVs1d5AB9ZXKdEOnxhJ5e8',
    appId: '1:253213775944:android:5d73843dc3a72bdcb7607d',
    messagingSenderId: '253213775944',
    projectId: 'gestionfournitures-2e8db',
    databaseURL: 'https://gestionfournitures-2e8db-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gestionfournitures-2e8db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFBsjYVK_o5410R3-Xo0x-bphyoH0gbUw',
    appId: '1:253213775944:ios:f2b13c9c560636b2b7607d',
    messagingSenderId: '253213775944',
    projectId: 'gestionfournitures-2e8db',
    databaseURL: 'https://gestionfournitures-2e8db-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gestionfournitures-2e8db.firebasestorage.app',
    iosBundleId: 'com.example.gestionFournitures',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFBsjYVK_o5410R3-Xo0x-bphyoH0gbUw',
    appId: '1:253213775944:ios:f2b13c9c560636b2b7607d',
    messagingSenderId: '253213775944',
    projectId: 'gestionfournitures-2e8db',
    databaseURL: 'https://gestionfournitures-2e8db-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gestionfournitures-2e8db.firebasestorage.app',
    iosBundleId: 'com.example.gestionFournitures',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLQ9SFqdDeeQxdDvHdeYCad4ZBEVINV5E',
    appId: '1:253213775944:web:a989e2302d7cd461b7607d',
    messagingSenderId: '253213775944',
    projectId: 'gestionfournitures-2e8db',
    authDomain: 'gestionfournitures-2e8db.firebaseapp.com',
    databaseURL: 'https://gestionfournitures-2e8db-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gestionfournitures-2e8db.firebasestorage.app',
  );
}
